version: '2.0'
volumes:
  db:
    driver: local
networks: {}
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: coherence_demo_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - db:/var/lib/postgresql/data:rw
    ports:
    - 5432:5432
